import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // {
    //   type: 'doc',
    //   label: '',
    //   id: 'README',
    // },
    { type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
